blogs/app/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from app import views


urlpatterns =[
    #注册
    url(r'^register/',views.register,name='register'),
    #登录
    url(r'^login/',views.login,name='login'),
    #首页
    url(r'^index/',login_required(views.index),name='index'),
    #退出登录
    url(r'^back_login/',views.back_login,name='back_login'),
    #进入文章
    url(r'^article/',views.article,name='article'),
    #进入公告
    url(r'^notice/',views.notice,name='notice'),
    #进入评论
    url(r'^comment/',views.comment,name='comment'),
    #进入栏目
    url(r'^category/',views.category,name='category'),
    #进入友情链接
    url(r'^flink/',views.flink,name='flink'),
    #基本设置
    url(r'^setting/',views.setting,name='setting'),
    #阅读设置
    url(r'^readset/',views.readset,name='readset'),
    #进入管理用户
    url(r'^manage_user/',views.manage_user,name='manage_user'),
    #进入管理登录日志
    url(r'^loginlog/',views.loginlog,name='loginlog'),
    #增加文章
    url(r'^add_article/',views.add_article,name='add_article'),
    #修改文章
    url(r'^update_article/(?P<num>\d+)',views.update_article,name='update_article'),
    #删除文章
    url(r'^del_article/(?P<num>\d+)',views.del_article,name='del_article'),
    # url(r'^guanli',views.guanli,name='gunali'),
#进入前端登录页面
    url(r'^loginw/',views.loginw,name='loginw')
    # url(r'^release',views.release,name='release')

]

blogs/blogs/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blogs import settings
from django.contrib.staticfiles.urls import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='app')),
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blogs/templates/add-article.html
{% extends 'base.html' %}

{% block title %}
写文章 - 博客管理系统
{% endblock %}
{% block extCss %}
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
{% endblock %}
{% block extJs %}
<script src="/static/js/jquery-2.1.4.min.js"></script>

  <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>


{#  <script>window.location.href='upgrade-browser.html';</script>#}

{% endblock %}
{% block content %}
<body class="user-select">
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">极限动力</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'app:back_login' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search" >
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="index.html">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
         <li><a  class="active" href="{% url 'app:article' %}">文章</a></li>
        <li ><a href="{% url 'app:notice' %}">公告</a></li>
        <li><a href="{% url 'app:comment' %}">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'app:category' %}">栏目</a></li>
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="{% url 'app:flink' %}">友情链接</a></li>
            <li><a href="{% url 'app:loginlog' %}l">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="manage-user.html">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'app:loginlog' %}">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="setting.html">基本设置</a></li>
            <li><a href="readset.html">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <form action="" method="post" class="add-article-form" enctype="multipart/form-data">
          <div class="col-md-9">
            <h1 class="page-header">撰写新文章</h1>
            <div class="form-group">
              <label for="article-title" class="sr-only">标题</label>
              <input type="text" id="article-title" name="title" class="form-control" placeholder="在此处输入标题" required autofocus autocomplete="off">
            </div>
            <div class="form-group">
              <label for="article-content" class="sr-only">内容</label>
              <script id="article-content" name="content" type="text/plain"></script>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>关键字</span></h2>
              <div class="add-article-box-content">
              	<input type="text" class="form-control" placeholder="请输入关键字" name="keywords" autocomplete="off">
                <span class="prompt-text">多个标签请用英文逗号,隔开。</span>
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>描述</span></h2>
              <div class="add-article-box-content">
              	<textarea class="form-control" name="describe" autocomplete="off"></textarea>
                <span class="prompt-text">描述是可选的手工创建的内容总结，并可以在网页描述中使用</span>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <h1 class="page-header">操作</h1>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>栏目</span></h2>
              <div class="add-article-box-content">
                <ul class="category-list">
                  <li>
                    <label>
                      <input name="category" type="radio" value="1" checked>
                      这是栏目 <em class="hidden-md">( 栏目ID: <span>1</span> )</em></label>
                  </li>
                  <li>
                    <label>
                      <input name="category" type="radio" value="2">
                      这是栏目 <em class="hidden-md">( 栏目ID: <span>2</span> )</em></label>
                  </li>
                  <li>
                    <label>
                      <input name="category" type="radio" value="3">
                      这是栏目 <em class="hidden-md">( 栏目ID: <span>3</span> )</em></label>
                  </li>
                  <li>
                    <label>
                      <input name="category" type="radio" value="4">
                      这是栏目 <em class="hidden-md">( 栏目ID: <span>4</span> )</em></label>
                  </li>
                  <li>
                    <label>
                      <input name="category" type="radio" value="5">
                      这是栏目 <em class="hidden-md">( 栏目ID: <span>5</span> )</em></label>
                  </li>
                </ul>
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>标签</span></h2>
              <div class="add-article-box-content">
                <input type="text" class="form-control" placeholder="输入新标签" name="tags" autocomplete="off">
                <span class="prompt-text">多个标签请用英文逗号,隔开</span> </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>标题图片</span></h2>
              <div class="add-article-box-content">
                <input type="file" class="form-control"  id="pictureUpload" name="image" autocomplete="off">
              </div>
{#              <div class="add-article-box-footer">#}
{#                <button class="btn btn-default" type="button" ID="upImage">选择</button>#}
{#              </div>#}
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>发布</span></h2>
              <div class="add-article-box-content">
              	<p><label>状态：</label><span class="article-status-display">未发布</span></p>
                <p><label>公开度：</label><input type="radio" name="visibility" value="0" checked/>公开 <input type="radio" name="visibility" value="1" />加密</p>
                <p><label>发布于：</label><span class="article-time-display"><input style="border: none;" type="datetime" name="time" value="2016-01-09 17:29:37" /></span></p>
              </div>
              <div class="add-article-box-footer">
                <a href=" "><button class="btn btn-primary" type="submit"   name="submit">发布</button></a>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>




<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
<script src="/static/lib/ueditor/ueditor.config.js"></script>
<script src="/static/lib/ueditor/ueditor.all.min.js"> </script>
<script src="/static/lib/ueditor/lang/zh-cn/zh-cn.js"></script>
<script id="uploadEditor" type="text/plain" style="display:none;"></script>
<script type="text/javascript">
var editor = UE.getEditor('article-content');
window.onresize=function(){
    window.location.reload();
}
var _uploadEditor;
$(function () {
    //重新实例化一个编辑器，防止在上面的editor编辑器中显示上传的图片或者文件
    _uploadEditor = UE.getEditor('uploadEditor');
    _uploadEditor.ready(function () {
        //设置编辑器不可用
        //_uploadEditor.setDisabled();
        //隐藏编辑器，因为不会用到这个编辑器实例，所以要隐藏
        _uploadEditor.hide();
        //侦听图片上传
        _uploadEditor.addListener('beforeInsertImage', function (t, arg) {
            //将地址赋值给相应的input,只去第一张图片的路径
            $("#pictureUpload").attr("value", arg[0].src);
            //图片预览
            //$("#imgPreview").attr("src", arg[0].src);
        })
        //侦听文件上传，取上传文件列表中第一个上传的文件的路径
        _uploadEditor.addListener('afterUpfile', function (t, arg) {
            $("#fileUpload").attr("value", _uploadEditor.options.filePath + arg[0].url);
        })
    });
});
//弹出图片上传的对话框
$('#upImage').click(function () {
    var myImage = _uploadEditor.getDialog("insertimage");
    myImage.open();
});
//弹出文件上传的对话框
function upFiles() {
    var myFiles = _uploadEditor.getDialog("attachment");
    myFiles.open();
}
</script>
</body>

{% endblock %}

blogs/templates/article.html
{%  extends 'base.html' %}

{% block extCss %}
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
{% endblock %}
{% block extJs %}
    <script src="/static/js/jquery-2.1.4.min.js"></script>
  <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>

<script>
function update(name) {

}
</script>
{#  <script>window.location.href='upgrade-browser.html';</script>#}
{% endblock %}
{% block content %}
<body class="user-select">
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">JackZeng</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ form.username.value }} <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'app:back_login' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'app:index' %}">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
         <li><a href="{% url 'app:article' %}">文章</a></li>
        <li ><a href="{% url 'app:notice' %}">公告</a></li>
        <li><a href="{% url 'app:comment' %}">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="category.html">栏目</a></li>
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="{% url 'app:flink' %}">友情链接</a></li>
            <li><a href="{% url 'app:loginlog' %}">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
             <li><a href="{% url 'app:manage_user' %}">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'app:loginlog' %}">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="{% url 'app:setting' %}">基本设置</a></li>
            <li><a href="{% url 'app:readset' %}">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <form action="/Article/checkAll" method="post" >
        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
          <li><a href="{% url 'app:add_article' %}">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge"></span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">关键字</span></th>
                <th class="hidden-sm"><span class="glyphicon glyphicon-tag"></span> <span class="visible-lg">描述</span></th>
                <th class="hidden-sm"><span class="glyphicon glyphicon-comment"></span> <span class="visible-lg">评论</span></th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>
            {% for content in text_content %}

            <tr>
                <td><input type="checkbox" class="input-control" name="checkbox[]" value="" /></td>

                <td class="article-title" >{{ content.title }}</td>
                <td>{{ content.keywords }}</td>
                <td class="hidden-sm">{{ content.describe }}</td>
                <td class="hidden-sm"></td>
                <td>2015-12-03</td>
                <td><a href="{% url 'app:update_article' content.id%}">修改</a> <a rel="6" href="{% url 'app:del_article' content.id%}" >删除</a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
              <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
              </div>
            </div>
            <ul class="pagination pagenav">
              <li class="disabled"><a aria-label="Previous"> <span aria-hidden="true">&laquo;</span> </a> </li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a> </li>
            </ul>
          </nav>
        </footer>
      </form>
    </div>
  </div>
</section>

<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
<script>
//是否确认删除
$(function(){
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id
		if (event.srcElement.outerText == "删除")
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/Article/delete",
					data: "id=" + id,
					cache: false, //不缓存此页面
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});
});
</script>
</body>


{% endblock %}

blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
{% block extCss %}

{% endblock %}
{% block extJs %}

{% endblock %}
</head>
<body>
{% block content %}


{% endblock %}
</body>
</html>

blogs/templates/ff.html
{% extends 'base.html' %}
{% block content %}
    你好
{% endblock %}

blogs/templates/indexw.html
{% extends 'base.html' %}
{% block title %}
我是个人博客界面
{% endblock %}

{% block extCss %}

<link href="/static/staticw/css/base.css" rel="stylesheet">
<link href="/static/staticw/css/index.css" rel="stylesheet">
<link href="/static/staticw/css/m.css" rel="stylesheet">
{% endblock %}
{% block extJs %}
<script src="/static/staticw/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/staticw/js/comm.js"></script>

<script src="/static/staticw/js/modernizr.js"></script>

{% endblock %}
{% block content %}
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="index.html">网站首页</a></li>
      <li><a href="share.html">我的相册</a></li>
      <li><a href="list.html">我的日记</a></li>
      <li><a href="about.html">关于我</a></li>
      <li><a href="gbook.html">留言</a></li>
      <li><a href="info.html">内容页</a></li>
      <li><a href="infopic.html">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/staticw/images/4.jpg"></i>
          <p><b>博客</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
      <div class="wdxc">

      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">

      </div>
      <div class="tuijian">

      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">个人博客</a> <a href="http://www.yangqq.com">博客</a>
        </ul>
      </div>
      <div class="guanzhu">

      </div>
  </aside>
  <main class="r_box">
      {% for content in page %}
      <li><i><a href="/"><img src="/media/{{ content.icon }}"></a></i>
          <h3><a href="/">{{ content.title }}</a></h3>
      <p>{{ content.content }}</p>

    </li>
          <p>当前页：{{ page.number }}</p>
    <p>页码：{% for i in page.paginator.page_range %}
    <a href="{% url 'app:loginw' %}?page={{ i }}">{{ i }}</a>
    {% endfor %}
    </p>
    <p>
    {%  if page.has_previous %}
    <a href="{% url 'app:loginw' %}?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
    {%  if page.has_next %}
     <a href="{% url 'app:loginw' %}?page={{ page.next_page_number }}">下一页</a>
    {% endif %}
    </p>
{% endfor %}

  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

blogs/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
我是注册页面
{% endblock %}
{% block extCss %}
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/login.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
{% endblock %}
{% block extJs %}
<script src="/static/js/jquery-2.1.4.min.js"></script>

  <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>


{#  <script>window.location.href='upgrade-browser.html';</script>#}
{% endblock %}
{% block content %}
<body class="user-select">
<div class="container">
  <div class="siteIcon"><img src="/static/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用博客管理系统" draggable="false" /></div>
  <form action="index.html" method="post" autocomplete="off" class="form-signin">
    <h2 class="form-signin-heading">管理员注册</h2>
    <label for="userName" class="sr-only">用户名</label>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd1" name="password" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
      <input type="password" id="userPwd" name="password2" class="form-control" placeholder="请确认密码" required autocomplete="off" maxlength="18">
    <a href="{% url 'app:index' %}"><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
  </form>
  <div class="footer">
    <p><a href="{% url 'app:login' %}" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">已有账号，去登录 →</a></p>
  </div>
</div>
<script src="/static/js/bootstrap.min.js"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
</body>
{% endblock %}